apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  annotations:
    arena.kubeflow.org/username: shuai.yang
  creationTimestamp: "2022-05-09T10:14:51Z"
  generation: 1
  labels:
    app: tfjob
    arena.kubeflow.org/uid: 28dae8cd8bb2b0159ce1cc8bc31ecb85
    chart: tfjob-0.35.0
    createdBy: TFJob
    heritage: Helm
    release: tf-estimator
  name: tf-estimator
  namespace: default
  resourceVersion: "120539419"
  uid: fc314a9f-91f6-4c95-bed3-946097e4b084
spec:
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: shuai.yang
            requestGPUsOfJobOwner: "3"
          labels:
            app: tfjob
            arena.kubeflow.org/uid: 28dae8cd8bb2b0159ce1cc8bc31ecb85
            chart: tfjob-0.35.0
            createdBy: TFJob
            heritage: Helm
            release: tf-estimator
        spec:
          containers:
          - command:
            - sh
            - -c
            - 'bash code/arena-tensorflow-sample-code/cheyang-models/dist_mnist_estimator.sh
              --log_dir=/log_dir/tf-estimator --data_dir=/data_dir/dataset/mnist/data
              --model_dir=/model_dir/tf-estimator'
            env:
            - name: gpus
              value: "1"
            - name: workers
              value: "1"
            image: registry.cn-shanghai.aliyuncs.com/shuaiyy/mihoyo-ai:arena-tf1.9-py27-gpu-mnist-distributed-estimator
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 20001
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /data_dir/
              name: ml-data-shuai-yang
            - mountPath: /log_dir/
              name: ml-log-shuai-yang
            - mountPath: /model_dir/
              name: ml-model-shuai-yang
            - mountPath: /summary_dir/
              name: ml-summary-shuai-yang
            workingDir: /root
          hostIPC: true
          hostPID: true
          tolerations:
          - key: gpu-pod
            operator: Exists
          volumes:
          - name: ml-data-shuai-yang
            persistentVolumeClaim:
              claimName: ml-data-shuai-yang
          - name: ml-log-shuai-yang
            persistentVolumeClaim:
              claimName: ml-log-shuai-yang
          - name: ml-model-shuai-yang
            persistentVolumeClaim:
              claimName: ml-model-shuai-yang
          - name: ml-summary-shuai-yang
            persistentVolumeClaim:
              claimName: ml-summary-shuai-yang
    Evaluator:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: shuai.yang
            requestGPUsOfJobOwner: "3"
          labels:
            app: tfjob
            arena.kubeflow.org/uid: 28dae8cd8bb2b0159ce1cc8bc31ecb85
            chart: tfjob-0.35.0
            createdBy: TFJob
            heritage: Helm
            release: tf-estimator
        spec:
          containers:
          - command:
            - sh
            - -c
            - 'bash code/arena-tensorflow-sample-code/cheyang-models/dist_mnist_estimator.sh
              --log_dir=/log_dir/tf-estimator --data_dir=/data_dir/dataset/mnist/data
              --model_dir=/model_dir/tf-estimator'
            env:
            - name: gpus
              value: "1"
            - name: workers
              value: "1"
            image: registry.cn-shanghai.aliyuncs.com/shuaiyy/mihoyo-ai:arena-tf1.9-py27-gpu-mnist-distributed-estimator
            imagePullPolicy: Always
            name: tensorflow
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /data_dir/
              name: ml-data-shuai-yang
            - mountPath: /log_dir/
              name: ml-log-shuai-yang
            - mountPath: /model_dir/
              name: ml-model-shuai-yang
            - mountPath: /summary_dir/
              name: ml-summary-shuai-yang
            workingDir: /root
          hostIPC: true
          hostPID: true
          tolerations:
          - key: gpu-pod
            operator: Exists
          volumes:
          - name: ml-data-shuai-yang
            persistentVolumeClaim:
              claimName: ml-data-shuai-yang
          - name: ml-log-shuai-yang
            persistentVolumeClaim:
              claimName: ml-log-shuai-yang
          - name: ml-model-shuai-yang
            persistentVolumeClaim:
              claimName: ml-model-shuai-yang
          - name: ml-summary-shuai-yang
            persistentVolumeClaim:
              claimName: ml-summary-shuai-yang
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: shuai.yang
            requestGPUsOfJobOwner: "3"
          labels:
            app: tfjob
            arena.kubeflow.org/uid: 28dae8cd8bb2b0159ce1cc8bc31ecb85
            chart: tfjob-0.35.0
            createdBy: TFJob
            heritage: Helm
            release: tf-estimator
        spec:
          containers:
          - command:
            - sh
            - -c
            - 'bash code/arena-tensorflow-sample-code/cheyang-models/dist_mnist_estimator.sh
              --log_dir=/log_dir/tf-estimator --data_dir=/data_dir/dataset/mnist/data
              --model_dir=/model_dir/tf-estimator'
            env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: gpus
              value: "1"
            - name: workers
              value: "1"
            image: registry.cn-shanghai.aliyuncs.com/shuaiyy/mihoyo-ai:arena-tf1.9-py27-cpu-mnist-distributed-estimator
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 20002
              name: tfjob-port
            resources:
              limits: null
              requests: null
            volumeMounts:
            - mountPath: /data_dir/
              name: ml-data-shuai-yang
            - mountPath: /log_dir/
              name: ml-log-shuai-yang
            - mountPath: /model_dir/
              name: ml-model-shuai-yang
            - mountPath: /summary_dir/
              name: ml-summary-shuai-yang
            workingDir: /root
          hostIPC: true
          hostPID: true
          tolerations:
          - key: gpu-pod
            operator: Exists
          volumes:
          - name: ml-data-shuai-yang
            persistentVolumeClaim:
              claimName: ml-data-shuai-yang
          - name: ml-log-shuai-yang
            persistentVolumeClaim:
              claimName: ml-log-shuai-yang
          - name: ml-model-shuai-yang
            persistentVolumeClaim:
              claimName: ml-model-shuai-yang
          - name: ml-summary-shuai-yang
            persistentVolumeClaim:
              claimName: ml-summary-shuai-yang
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: shuai.yang
            requestGPUsOfJobOwner: "3"
          labels:
            app: tfjob
            arena.kubeflow.org/uid: 28dae8cd8bb2b0159ce1cc8bc31ecb85
            chart: tfjob-0.35.0
            createdBy: TFJob
            heritage: Helm
            release: tf-estimator
        spec:
          containers:
          - command:
            - sh
            - -c
            - 'bash code/arena-tensorflow-sample-code/cheyang-models/dist_mnist_estimator.sh
              --log_dir=/log_dir/tf-estimator --data_dir=/data_dir/dataset/mnist/data
              --model_dir=/model_dir/tf-estimator'
            env:
            - name: gpus
              value: "1"
            - name: workers
              value: "1"
            image: registry.cn-shanghai.aliyuncs.com/shuaiyy/mihoyo-ai:arena-tf1.9-py27-gpu-mnist-distributed-estimator
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 20000
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /data_dir/
              name: ml-data-shuai-yang
            - mountPath: /log_dir/
              name: ml-log-shuai-yang
            - mountPath: /model_dir/
              name: ml-model-shuai-yang
            - mountPath: /summary_dir/
              name: ml-summary-shuai-yang
            workingDir: /root
          hostIPC: true
          hostPID: true
          tolerations:
          - key: gpu-pod
            operator: Exists
          volumes:
          - name: ml-data-shuai-yang
            persistentVolumeClaim:
              claimName: ml-data-shuai-yang
          - name: ml-log-shuai-yang
            persistentVolumeClaim:
              claimName: ml-log-shuai-yang
          - name: ml-model-shuai-yang
            persistentVolumeClaim:
              claimName: ml-model-shuai-yang
          - name: ml-summary-shuai-yang
            persistentVolumeClaim:
              claimName: ml-summary-shuai-yang
